GET /projects
Host: localhost:9090
Content-Type: application/json

###

POST /projects
Host: localhost:9090
Content-Type: application/json

{
  "projectStatusId": 2,
  "projectName": "프로젝트 이름",
  "requestMembers": [
    {
      "projectMemberId": "id1",
      "projectRole": "role1"
    },
    {
      "projectMemberId": "id2",
      "projectRole": "role2"
    }
  ]
}





###

PUT /projects/124
Host: localhost:9090
Content-Type: application/json

{
  "name": "name"
}