GET /projects/1/tags
Host: localhost:9090
Content-Type: application/json

###
POST /projects/1/tags
Host: localhost:9090
Content-Type: application/json

{
  "tagName" : "tagCode"
}


###
PUT /projects/1/tags/14
Host: localhost:9090
Content-Type: application/json

{
  "tagName" : "tag14"
}

###
DELETE /projects/1/tags/14
Host: localhost:9090
Content-Type: application/json

